source 'https://rubygems.org'

gem 'rails', '4.1.7'
gem 'pg', '0.18.0'
gem 'uglifier', '>= 1.3.0'
gem 'therubyracer',  platforms: :ruby
gem 'jbuilder', '~> 2.0'
gem 'tzinfo', :platform => :ruby
gem 'tzinfo-data', :platform => [:mingw, :mswin, :x64_mingw]
gem "font-awesome-rails"
gem 'bootstrap-sass', '~> 3.3.7'
gem 'sass-rails', '>= 3.2'
gem 'turbolinks'
gem 'devise'
gem 'rails-ujs'
gem 'jquery-rails'