development:
  adapter: postgresql
  encoding: utf8
  database: galaxia_db
  host: localhost
  port: 5432
  pool: 5
  username: kanth_user
  password: kanth5310

production:
  adapter: postgresql
  encoding: utf8
  database: galaxia_db_production
  host: localhost
  pool: 5
  port: 5432
  username: kanth_user
  password: kanth5310
